### ISSUE TITLE
Verksamhetsområden

### ISSUE THREAD

**Issue by Fijo-Lurk** [chas-academy/u02-redesign-sputnik#3]
- [x] Brainstorming / Prototyping
- [x] Design
- [x] Code

**Comment by natalienilsson93** [comment]
Have been assigned to create a prototype for "Verksamhetsområden".

**Comment by natalienilsson93** [comment]
CSS and HTML is done, only the hamburger-menu have to be fixed.

**Comment by Fijo-Lurk** [comment]
hamburger-menu is working as intended now.
