### ISSUE TITLE
kontakt

### ISSUE THREAD

**Issue by Fijo-Lurk** [chas-academy/u02-redesign-sputnik#9]
- [x] Brainstorming / Prototyping
- [x] Design
- [x] Code

**Comment by Sami-Olsson** [comment]
I will take care of Kontakt

**Comment by natalienilsson93** [comment]
Took over this project, html and CSS is done. 
I will continue with responsively and accessibility.

**Comment by Fijo-Lurk** [comment]
responsively and accessibility is done!
